version: "2.4"

secrets:
  nginx-crt:
    file: ../nginx-repo.crt
  nginx-key:
    file: ../nginx-repo.key

services:
  nginx-plus:
    container_name: nginx-plus
    image: nginx-plus
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - nginx-crt
        - nginx-key
      args:
        NGINX_PLUS_VERSION: 31
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080-8081:8080-8081"

  nginx:
    container_name: nginx
    image: docker.io/nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080-8081:8080-8081"
