name: test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: create env
      run: make env
    - name: run test
      run: make trigger
